name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git setup
      run: git clone https://github.com/RahifM/scripts && bash sc*/misc*
    - name: clone
      run: git clone https://github.com/sabmohmaya/mido -b staging/f2fs-2/lineage-15.1

    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
