name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
    - uses: actions/checkout@v2
    - name: git setup
      run: sh ./linux.sh
    #  run: git clone https://github.com/RahifM/scripts && bash sc*/misc*

    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
